spring:
  application:
    name: eureka-server
 
server:
  port: ${PORT:8761}
 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaservicereg-peer1.emea.fe.gopivotal.com/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'